apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: id-generator-server
spec:
  selector:
    app: id-generator-server
  ports:
    - protocol: TCP
      port: 5189
      targetPort: 5189
  type: ClusterIP
  